# Generated by Django 3.0.4 on 2020-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
