# Generated by Django 3.1.7 on 2021-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='api_id',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='show',
            name='api_id',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='api_id',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('name', 'api_id')},
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('artist', 'api_id')},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'api_id')},
        ),
    ]
