# Generated by Django 3.1.2 on 2020-12-06 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lmn', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='display_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='favorite_genres',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
