# Generated by Django 3.1.2 on 2020-12-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_auto_20201117_1954'),
        ('lmn', '0002_auto_20201201_1807'),
    ]

    operations = [
    ]
