# Generated by Django 3.1.7 on 2021-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lmn/media/user_images/'),
        ),
    ]
