# Generated by Django 3.1.7 on 2021-05-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_profile'),
        ('lmn', '0003_auto_20210510_1405'),
    ]

    operations = [
    ]
