# Generated by Django 3.1.7 on 2021-05-11 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_auto_20210510_1405'),
        ('lmn', '0003_auto_20210510_1710'),
    ]

    operations = [
    ]
