# Generated by Django 3.1.7 on 2021-05-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_merge_20210510_2204'),
        ('lmn', '0004_merge_20210511_1616'),
    ]

    operations = [
    ]
