# Generated by Django 3.1.7 on 2021-05-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_merge_20210511_1001'),
        ('lmn', '0005_merge_20210511_2209'),
    ]

    operations = [
    ]
