# Generated by Django 3.1.7 on 2021-05-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0006_auto_20210511_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('artist', 'api_id')},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'api_id')},
        ),
    ]
